name: Application Deployment on a Compute Engine VM

on:
  push:
    paths:
      - 'app/**' # Trigger on changes to application files

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Authenticate with GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Step 3: Deploy Application via SSH
      - name: Deploy App
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.GCE_VM_IP }}
          username: ${{ secrets.GCE_USERNAME }}
          key: ${{ secrets.GCE_PRIVATE_KEY }}
          script: |
            sudo apt-get update
            sudo apt-get install -y nginx
            echo "Hello, World!" > /var/www/html/index.html
            sudo systemctl restart nginx

      # Scan Docker Images for Vulnerabilities
      - name: Scan Docker Images
        uses: aquasecurity/trivy-action@v0.29.0
        with:
          image-ref: "gcr.io/your-project-id/hello-world-app:latest"

