name: Terraform Deployment

on:
  push:
    paths:
      - 'terraform/**' # Trigger on changes to Terraform files
  workflow_dispatch: # Allow manual triggers

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Step 3: Initialize Terraform
      - name: Terraform Init
        run: terraform -chdir=terraform init

      # Step 4: Plan Terraform
      - name: Terraform Plan
        run: terraform -chdir=terraform plan

      # Step 5: Apply Terraform (on push only)
      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform -chdir=terraform apply -auto-approve
